tdlib/td

- tdutils/td/utils/port/path.h
It fixes an error that happens during building on Alpine Linux:
```
In file included from /tmp/td/tdutils/td/utils/port/path.cpp:7:0:
/tmp/td/tdutils/td/utils/port/path.h: In function 'td::Status td::walk_path(td::CSlice, Func&&)':
/tmp/td/tdutils/td/utils/port/path.h:167:21: error: 'PATH_MAX' was not declared in this scope
curr_path.reserve(PATH_MAX + 10);
^~~~~~~~
```
> Add missing <limits.h> so PATH_MAX would be available

- td/generate/scheme/td_api.tl
Clarify that the message id is unique to the chat it belongs to.
See https://github.com/tdlib/td/issues/245
> Clarify the message id description (fixes #245)

- tdutils/td/utils/logging.h
In tdutils/td/utils/logging.h it had the non-standard \e escape, which causes some warnings when compiling in standard mode (or errors with -Werror) so I replaced it with the standard hex escape sequence.
> Use standard escape sequences

- tdtl/td/tl/tl_config.cpp
In English the right word is "version" instead of "verdion" which has no meaning in the language.
Just replace the word with the correct one
> Fix typo mistake

- CMakeLists.txt
Added SOVERSION to shared libraries.
SOVERSION required for all major GNU/Linux distributions.
> Added SOVERSION to shared libraries

- example/web/tdweb/src/worker.js
When attempting to run the asmjs version of tdweb, I ran into a few issues. This PR fixes them:
1. `log.warning` is replaced with the correct call, `log.warn`
1. `Module.default` is used as opposed to `Module`
> Fix for loading asm.js version of tdweb

- tdutils/td/utils/port/detail/ThreadPthread.cpp
* Alpine doesn't use sys/sysctl header for syscalls
* Error log: https://del.dog/ujofeqowol
> tdutils: Fix build for alpine linux

- tdnet/td/net/HttpProxy.cpp
see https://github.com/tdlib/td/issues/1043
> Surround IPv6 addresses by square braquets in HTTP CONNECT requests

- td/telegram/MessagesManager.cpp
- td/telegram/Td.cpp
This option allows to override the default dialog unload delay.
The allowed range is from 0 to 86400 seconds (1 day).
Setting the value -1 restores the default behavior.
If the option is not set the default value will be -1, so it will use the default behavior.
> Option "chat_unload_delay" for bots

- example/java/org/drinkless/tdlib/example/Example.java
Java build failed with error 
```
/Users/nikitakulikov/private/tdlib-lionzxy/example/java/org/drinkless/tdlib/example/Example.java:308: error: no suitable constructor found for LogStreamFile(String,int)
if (Client.execute(new TdApi.SetLogStream(new TdApi.LogStreamFile("tdlib.log", 1 << 27))) instanceof TdApi.Error) {
^
constructor LogStreamFile.LogStreamFile() is not applicable
(actual and formal argument lists differ in length)
constructor LogStreamFile.LogStreamFile(String,long,boolean) is not applicable
(actual and formal argument lists differ in length)
Note: /Users/nikitakulikov/private/tdlib-lionzxy/example/java/org/drinkless/tdlib/Client.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
make[2]: *** [CMakeFiles/build_java] Error 1 …
```
> Fix java example build

- example/cpp/td_example.cpp
`std::cin` only reads the first word from the command-line, while Telegram passwords can contain spaces
> Minor bug fix in the cpp example

- td/telegram/MessageContentType.h
- td/telegram/MessagesManager.cpp
See issue #1282 for more details.
> Implement hash function for MessageContentType enum.

- td/telegram/logevent/LogEventHelper.cpp
Looks like an artifact of copy paste or something like that.
It forces us to add additional include directory to the root of tdlib sources `-I.` near with correct `-Itddb`.
Grep shows that this is the single source file with `/td/` (or `\/td\/`) pattern that adds something before root `td/` part.
> Remove extra include dir part.

- tdutils/CMakeLists.txt
- tdutils/td/utils/port/FileFd.cpp
- tdutils/td/utils/port/FromApp.h
- tdutils/td/utils/port/path.cpp
This change only affects UWP apps.
*FromApp methods are loaded dynamically to preserve backward compatibility (Method was introduced in Windows 10, version 17134).
This allows TDLib to read and write outside app local folder, if specified `FilesDirectory` is accessible by the app.
> Use *FromApp methods when available

- example/README.md
Приветствую.
Пару часов назад релизнул [rust-tdlib 0.2.0](https://crates.io/crates/rust-tdlib) и только после этого чисто случайно наткнулся на [одноименную библиотеку](https://github.com/lattenwald/rust-tdlib), и то только потому, что она упомянута здесь: библиотеки нет на crates.io, поэтому с названием и не возникло проблем.
Я написал разработчику библиотеки, указанной в ридми и он не против изменить ссылку на мой вариант (можете убедиться в этом, поискав на сервере телеграма :D):
```
Alexander, [17.02.21 12:09]
Со мной связались за два года про эту либу один раз, ты второй.
Alexander, [17.02.21 12:09]
Клиент, вероятно, людям удобнее
Alexander, [17.02.21 12:09]
Заменяй
```.
> change rust-tdlib link

- example/cpp/td_example.cpp
> Fix memory leak of "handlers_" in cpp example

- CMakeLists.txt
By changing the mode of a few libraries from STATIC to OBJECT
when BUILD_SHARED_LIBS is enabled, CMake will output a shared
library object that doesn't require any static linking against
Td from the library user's end.
> Make BUILD_SHARED_LIBS yield dynamic lib that doesn't need static libs

- example/ios/README.md
I've tried to build `TDLib`for iOS and found out that some files are generated only for macOS builds. 
I want to propose a change for docs because i've naturally skipped pregeneration docs part due to weak "`can`" word. 
I've tried to build `TDLib` for iOS only and failed because some **required** files were missing.
So we definitely **`must`** pregenerate files if we don't want to build macOS lib in a same flow (pipeline, etc)
Example behaviour below
error, unable to find some generated tdutils file
sources generated "on the fly" in same build phase
sources generated with separate command
> Clarify importance of generated files on non-macOS builds

- example/python/tdjson_example.py
automatically sends the message to `stderr` and sets the exit-code to 1
`quit` is only for exiting the interpreter, use the recommended `sys.exit`
> Update python example: Use sys.exit for quitting

- CMake/iOS.cmake
Well, I don't want to build for all default archs, so I added the `if (NOT DEFINED IOS_ARCH)` part to let users customize the `IOS_ARCH` value
> Ability to override default value of IOS_ARCH

- CMake/TdSetUpCompiler.cmake
- td/generate/scheme/td_api.tl
- td/mtproto/SessionConnection.cpp
- td/telegram/MessagesManager.cpp
- td/telegram/NotificationManager.cpp
- td/telegram/PollManager.cpp
- td/telegram/net/Session.cpp
- tdnet/td/net/HttpHeaderCreator.h
- tdnet/td/net/HttpReader.cpp
- tdutils/td/utils/OptionParser.cpp
There was an error message that incorrectly said ”too much parameters“ while it should be “too many parameters” since parameters are countable. This PR fixes it.
Along the way, it also fixes the same mistake in a bunch of other places. However, only comments, documentation, logs, and error messages are touched. For example, `checkChatUsernameResultPublicChatsTooMuch` is left unchanged in order to avoid a breaking change.
> Fix typos regarding much and many

- td/generate/scheme/td_api.tl
- td/telegram/LinkManager.cpp
- td/telegram/LinkManager.h
- test/link.cpp
This pull request adds support for more `tg://settings` links:
* `tg://settings/theme` - from the iOS client
* `tg://settings/language` - from Telegram Desktop
* `tg://settings/privacy` - from the native macOS client
These could be defined "non-standard" links, but some of the already implemented ones (such as `tg://settings/change_number`) are non-standard as well.
> Add more Settings links

- example/README.md
The tdgrand library has been renamed to just 'tdlib'.
> Update renamed tdlib rust lib.

- build.html
I made some additional visual (and accessibility) changes in addition to #1689:
My previous pull request (#1689) had some problems:
- The focus visuals caused side effects
- The native focus visuals were removed which broke navigation with keyboard (which was reverted)
These changes bring new focus visuals which do not have side-effects and are present in all elements (but some are not triggered by mouse)
The build instructions generator looked terrible on mobile devices:
- Font size was too small and inconsistent
- Command list would overflow if commands were long
Both of them have been fixed.
Checkboxes and radio buttons were 1px / 2px below the perfect alignment with their labels. They have been moved to fix this.
***
Preview: https://mammad900.github.io/td/build.html
> Further improvements and fixes for build instructions generator

- td/generate/scheme/td_api.tl
- td/telegram/Account.cpp
This pull request adds a new `type` field to the `session` class, which can be used by graphical clients to display a corresponding icon.
*Currently, apps are supposed to parse session parameters themselves to detect its type, which can lead to inconsistencies.*
I used the same conditions as the official [iOS](https://github.com/TelegramMessenger/Telegram-iOS/blob/f95cfbdc42bee2b4ee92750ca2bda0e85d68e942/submodules/SettingsUI/Sources/Privacy%20and%20Security/Recent%20Sessions/ItemListRecentSessionItem.swift#L113) and [macOS](https://github.com/overtake/TelegramSwift/blob/13d62c1c03df7dea70bad0f395fb68115f5a0b43/Telegram-Mac/RecentSessionsController.swift#L19) apps, and [Unigram](https://github.com/UnigramDev/Unigram/blob/4870c5ef42d757c93297da2fbafa29fc04c97f38/Unigram/Unigram/Controls/Cel …
> Add session type field

- tdutils/td/utils/port/detail/ThreadStl.h
This PR fixes two compilation error in MinGW-w64 under MSYS:
1. **Thread compilation error: invalid conversion**
Same problem has been found here: https://github.com/boostorg/fiber/pull/281. In TDLib it happens in `tdutils/td/utils/port/detail/ThreadStl.h` and adding `reinterpret_cast<HANDLE>` fixes it.
2. **cc1plus.exe: out of memory**
This happens only in 32-bit MinGW build. `td/telegram/MessagesManager.cpp` gives an out of memory error. There is an [old compiler bug in GCC](https://sourceforge.net/p/mingw-w64/mailman/message/33182613/) which either wasn't fixed or reappeared again. Adding `-ftrack-macro-expansion=0` to compiler flags solves the problem.
Moved to #2212 by request.
> Fix MinGW threading compilation error

- CMake/TdSetUpCompiler.cmake
Moved from #2210 with changes suggested in its comments.
This PR fixes `cc1plus.exe: out of memory` error in 32-bit MinGW build. td/telegram/MessagesManager.cpp gives an out of memory error. There is an [old compiler bug in GCC](https://sourceforge.net/p/mingw-w64/mailman/message/33182613/) which either wasn't fixed or reappeared again. Adding `-ftrack-macro-expansion=0` to compiler flags solves the problem.
> Fix MinGW (32-bit) out of memory error

- example/README.md
Third-party Go packages are named after Git repository URLs, which could cause confusion if some libraries are bearing the same name. [go-tdlib](https://github.com/zelenin/go-tdlib) and [go-tdlib](https://github.com/Arman92/go-tdlib) are just some examples which may confuse people. So I added their canonical package names according to Go package registry.
> Clarify package names for Go

- td/generate/scheme/td_api.tl
The `source` argument should be marked as maybe null, not the `force_reply` argument.
> Fix a type on viewMessages method documentation.

- tdnet/td/net/DarwinHttp.mm
Attempts to fix a part of #2499, comment:
> Here's the interesting thing that I observed today, even after re-enabling IPv4 (and at the point where IPv4 websites are already usable in Safari), the errors still keep streaming in, and attempting to open a chat (or do anything basically, that being an example), just didn't work.
I made this minor change, observation seems to suggest that this at least recovers after connection is loss, rather than just not working at all after connection loss. (It does not change any IPv6 behaviour mentioned in the same issue)
> waitsForConnectivity, configurations for URLSession

- CMake/iOS.cmake
Fix #2604. 
Have yet to have the time to fully test this; will do test things out again fully tomorrow. Currently seeing good signs as was able to clear the first few files that failed to compile previously.
Will remain draft for now until I make sure things are alright.
Believe issue is due to:
> Several incidental transitive includes have been removed from libc++. Those includes are removed based on the language version used. If you see errors related to missing std:: entities in your code after upgrading, ensure you have all required includes.
(source: https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Deprecations)
> Fix building with Xcode 15

- example/java/org/drinkless/tdlib/Client.java
`Client.execute` in Java interface is now strongly typed: returned TDLib object type depends on the return type defined in the corresponding Function class.
When TDLib error is occurred, method now throws `Client.ExecutionError`.
This change adds compile-time protection against return type change and allows using this pattern:
```
try {
TdApi.SpecificReturnType result = Client.execute(function);
// work with strongly typed resultl without casting and type checks
} catch (Client.ExecutionError error) {
// Handle error
}
```
> Strongly typed API for synchronous TDLib method execution in Java interface

- CMake/iOS.cmake
See CMP0153
iOS builds fail. https://github.com/Swiftgram/TDLibFramework/actions/runs/7299002751/job/19891100843
> Change deprecated `exec_program` to `execute_process` in iOS.cmake

- td/telegram/DialogActionManager.cpp
The [code recently introduced in `DialogActionManager::send_dialog_action`](https://github.com/tdlib/td/commit/b684039566057385228e8b6a06ab6afcc05277f6#diff-bce63a6e456e5472a3ffac1f725c5f2a02285d243c50001366b3dcc79f472888R292-R313) makes the assumption that, since we'd either have early returned or `DialogManager::have_input_peer` would return true; that the else block of the conditional, which intended to set `input_peer`, should have done so successfully.
However, [`DialogManager::have_input_peer` will return true for secret chats when `contacts_manager->have_input_encrypted_peer`](https://github.com/tdlib/td/blob/4bafdc2b7129694c5b1b36eb7109043f92f13a0a/td/telegram/DialogManager.cpp#L632-L635)
And [`DialogManager::get_input_peer` will return a `nullptr` for secret …
> Fix DialogActionManager::send_dialog_action in secret chats

- example/java/org/drinkless/tdlib/Client.java
`//noinspection unchecked` suppresses unchecked cast warning only in the IDE. `@SuppressWarning` annotation properly suppresses both IDE and the compiler warnings.
> Replace `noinspection` instruction with proper `@SuppressWarnings` annotation

- td/telegram/InlineQueriesManager.cpp
This option was renamed more than a year ago. Bots that are developed today are likely to work with the updated Bot API specification, i.e. use `start_parameter` instead of the previous option `switch_pm_parameter`.
The error message should be updated in order to be more helpful. This pull request does that.
> Improve error message for empty start_parameter.

- tdutils/td/utils/JsonBuilder.cpp
- tdutils/td/utils/JsonBuilder.h
When I tried to build using clang 16 and c++20, I got a compilation error like this:
```
In file included from /home/mikhnenko/libs/tdlib/td/telegram/ClientJson.cpp:7:
In file included from /home/mikhnenko/libs/tdlib/td/telegram/ClientJson.h:9:
In file included from /home/mikhnenko/libs/tdlib/td/telegram/Client.h:11:
In file included from /home/mikhnenko/libs/tdlib/td/generate/auto/td/telegram/td_api.h:3:
In file included from /home/mikhnenko/libs/tdlib/td/tl/TlObject.h:16:
In file included from /home/mikhnenko/libs/cxxsupp/libcxx/include/string:574:
In file included from /home/mikhnenko/libs/cxxsupp/libcxx/include/__functional/hash.h:24:
/home/mikhnenko/libs/cxxsupp/libcxx/include/__utility/pair.h:90:9: error: field has incomplete type 'td::JsonValue'
_T2 second;
^ …
```
> Moved the use of methods marked constexpr since c++20 to forward declared types

- CMakeLists.txt
https://cmake.org/cmake/help/v3.0/module/CTest.html explains that including the `CTest` module and using the created `BUILD_TESTING` option allows users to opt out of creating tests when testing isn't desired.
This is what I would usually submit to projects, where using it via `add_subdirectory()` from another project is not a consideration. Since `BUILD_TESTING` is a cache variable, is this a problem again? So maybe just
```cmake
if (BUILD_TESTING)
enable_testing()
add_subdirectory(test)
endif()
```
…without including `CTest` (since that's what defines the `option()`)? Though this would default to the tests not being built, while using the `option()` would [preserve current behaviour](https://github.com/Kitware/CMake/blob/v3.0.2/Modules/CTest.cmake#L80)…
> Allow opting out of test building

- CMakeLists.txt
Closes #3090, by removing the option to build `tdapi` & `tdclient` as shared libraries, as mentioned in https://github.com/tdlib/td/issues/3090#issuecomment-2419445554.
> Remove ability to build tdapi & tdclient dynamically

- example/uwp/SDKManifest.xml
- example/uwp/build.ps1
This uses an array for `-arch` parameter that's validated by PowerShell directly.
Allows to specify multiple architectures at once without having to build either all of them or just one.
> Improve UWP build script

- example/python/tdjson_example.py
I've been working with TDLib for a **few personal projects and noticed the Python example could use some improvements to make it more accessible to newcomers**. After struggling with some aspects of the example myself, I decided to rewrite it while keeping all the functionality intact.
The main changes:
**- Restructured the code into a proper class to make it easier to reuse**
**- Added better error messages and prompts during the authentication flow**
**- Improved documentation so new users understand what each part does**
**- Added type hints for better IDE support**
**- Separated the authentication logic from the main loop for clarity**
**I just made it easier to understand and extend. The new version should be a drop-in replacement that works exactly the same way but with a cleaner …
> Update tdjson_example.py to a new clean structure.

- td/telegram/cli.cpp
The outer condition checks if op is one of `"sclpsv", "sclpsp" or "sclpsd"` where the inner condition checks against `"sclsv" and "sclsp"`.
Enums will be a great choice here, as the code grows you have to keep track of the exact string option. However,  you may also consider using a static analysis tool such as [**Cppcheck**](https://github.com/danmar/cppcheck) to detect issues like this. You might also integrate it into a CI workflow for automated checks.
Have a great day!
> Fix unreachable inner if condition

- td/generate/tl-parser/tl-parser.c
Ensure `FILE*` f is closed on failure
> Fix potential resource leak

- tdutils/td/utils/Ed25519.cpp
When being built under cmake's Release mode,  there is merely one warning:
```
/home/micdeb/repo/td/tdutils/td/utils/Slice.h:266:14: warning: array subscript 31 is outside array bounds of ‘const char [1]’ [-Warray-bounds]
266 |   return s_[i];
|              ^
```
currently detected on platforms: GCC 12 on Linux
> Suppress GCC warnings

- td/telegram/DialogActionBar.cpp
`lhs.is_join_request_broadcast_` was compared with itself.
> Fix DialogActionBar operator== condition

- example/ios/build.sh
Cmake got updated recently and now `brew`'s default version is v4. TDLib Apple builds fail if `CMAKE_MAKE_PROGRAM` is not set. This PR explicitly sets this value. 
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
`macOS` buids are not affected. Make sure to run any other Apple target when you'll be testing this.
My guess it's due to using `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY` in [CMake/iOS.cmake](https://github.com/tdlib/td/blob/086b549dbbc16c09bbf1b03ad8c87848f37b88a6/CMake/iOS.cmake#L256). I [once pointed out](https://t.me/tdlibchat/108339) it's a reason why `find_program(CCACHE_FOUND ccache)` doesn't work for iOS builds.
Perhaps we should try to use …
> Fix iOS build with cmake v4

- example/android/CMakeLists.txt
Starting November 1st, 2025, the ELF segments for shared libraries will have to be 16 KB aligned:
https://developer.android.com/guide/practices/page-sizes
> Android: Enable 16 KB ELF alignment for `arm64-v8a` and `x86_64` platforms

- CMakeLists.txt
- td/generate/CMakeLists.txt
- td/generate/DotnetTlDocumentationGenerator.php
- td/generate/TlDocumentationGenerator.php
Generate XML documentation for .NET API instead of annotating source files and rely on the compiler for XML generation.
This fixes some issues with vectors, as well adds support for C++/WinRT documentation.
> Generate XML documentation for .NET API
